# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14b5dde2e1cdb2b341c93eedca0fbed6df9ee3f45f5721872e8f366d1742de9cbd0ea042ffb70eccffc15583d090f26a434bf986425b402bf3b52b87b32ce786

test:
  secret_key_base: 859dd19c60cd5f48753956557d92e6ef2787febb89cb52c9cb9bf614dccf90134e49424c3997b7403e628a2e0697ae89d5ba7b36d97349fc07decde4316cfbda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
